MoonchildProductions/moebius

build/release/info.py, build/variables.py
After this merge Build ID will be generated in UTC.
https://github.com/MoonchildProductions/moebius/issues/14
=> This PR fixes timezone issue with Build ID

browser/locales/Makefile.in, testing/mozharness/configs/single_locale/linux32.py
This PR fixes a broken symlink (so my Git client will stop complaining about it constantly), and fixes packaging for Basilisk.
=> Couple small fixes

browser/themes/windows/browser-aero.css
Follow-up to #34 
Turns out I forgot to remove a few lines. Go figure.
=> Windows 10 fixes

browser/components/contextualidentity/test/browser/browser_forgetaboutsite.js, browser/components/migration/tests/unit/test_Chrome_cookies.js, browser/components/places/content/controller.js, browser/components/sessionstore/test/browser_394759_purge.js, browser/components/sessionstore/test/browser_464199.js, dom/indexedDB/test/browser_forgetThisSite.js, toolkit/forgetaboutsite/ForgetAboutSite.jsm, toolkit/forgetaboutsite/test/browser/browser_clearplugindata.js, toolkit/forgetaboutsite/test/unit/test_removeDataFromDomain.js
Ad #32
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1247201
---
__A warning - it is not tested!__
=> ForgetAboutSite.jsm - promise - serialize vs. parallel

devtools/client/shared/curl.js
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1182
---
__It's a small change, bug a warning - it is not tested!__
=> [regression] DevTools - network - Copy as cURL (http versions)

toolkit/content/aboutSupport.js, toolkit/content/aboutSupport.xhtml, toolkit/mozapps/update/content/history.js
https://github.com/MoonchildProductions/Pale-Moon/pull/768
https://github.com/MoonchildProductions/Pale-Moon/commit/61ce72d7ad1702a784960680e1f4bff16db53a04
https://github.com/MoonchildProductions/Pale-Moon/pull/729
---
__It's a small change, bug a warning - it is not tested!__
=> [regression] Build - the updater

toolkit/components/places/BookmarkHTMLUtils.jsm
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/996
---
__It's a small change, bug a warning - it is not tested!__
=> [regression] Places - proper import bookmarks from HTML containing <HR> separators

docshell/base/nsAboutRedirector.cpp
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/671
---
__It's a small change, bug a warning - it is not tested!__
=> [regression] about:license - the link to about:buildconfig

toolkit/content/aboutSupport.js
Ad https://github.com/MoonchildProductions/moebius/pull/40 - follow up (no preprocessing).
---
=> [regression] Build - the updater - follow up

toolkit/components/alerts/resources/content/alert.js, toolkit/components/alerts/resources/content/alert.xul
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/544 (https://github.com/MoonchildProductions/Pale-Moon/pull/878)
---
You add the label `Web Compatibility` (?), please.
The original label `UXP-task` can be removed.
---
=> Notifications - Run (Desktop) Notifications twice (and more) in a row does not work

netwerk/base/nsICryptoHash.idl, services/crypto/modules/utils.js
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/914
---
You add the label `Extensions` / `Front-end` / `Security` / `Web Compatibility` (?), please.
The original label `UXP-task` can be removed.
---
=> Crypto Services (utils) - Support for SHA224-512

dom/url/URL.h, dom/url/tests/test_url.html, dom/webidl/URL.webidl
Ad #48
(https://github.com/MoonchildProductions/Pale-Moon/pull/1117)
---
=> JS - URL - add toJSON support

docshell/test/file_bug1151421.html, docshell/test/mochitest.ini, docshell/test/navigation/file_scrollRestoration.html, docshell/test/test_bug1151421.html, docshell/test/test_bug1186774.html, docshell/test/test_bug590573.html, docshell/test/test_bug653741.html, docshell/test/test_bug662170.html, dom/base/nsGlobalWindow.cpp, dom/base/nsGlobalWindow.h, dom/base/test/test_viewport_scroll.html, dom/browser-element/mochitest/browserElement_ScrollEvent.js, dom/tests/mochitest/general/test_domWindowUtils_scrollXY.html, dom/webidl/Window.webidl, layout/forms/test/test_bug562447.html, layout/forms/test/test_bug564115.html
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1115
---
You add the label `Web Compatibility` (?), please.
The original label `UXP-task` can be removed.
---
=> JS - make window.pageYOffset/pageXOffset/scrollX/scrollY double

dom/html/nsTextEditorState.cpp, dom/html/nsTextEditorState.h, editor/libeditor/tests/mochitest.ini, editor/libeditor/tests/test_bug1352799.html
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1114
(https://bugzilla.mozilla.org/show_bug.cgi?id=1352799)
---
=> HTML - input - dynamic maxlength didn't work

devtools/shared/gcli/commands/cookie.js
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1198
---
---
=> DevTools - gcli commands - cookie

toolkit/content/aboutSupport.js, toolkit/content/aboutSupport.xhtml
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1093
`Places Database` - `Verify` -> `Copy text to clipboard`
(copying the result)
---
=> about:support - improvements (Copy text to clipboard)

browser/components/nsBrowserContentHandler.js, browser/components/shell/nsSetDefaultBrowser.js, devtools/client/devtools-startup.js, layout/tools/recording/recording-cmdline.js, toolkit/xre/nsAppRunner.cpp
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1019
1)
`-help` - the columns alignment
2)
`Unable to start debugger server` -> write also to the console
---
---
=> Basilisk - the cmd line - help (the columns alignment, error improvements)

toolkit/content/aboutSupport.js
Ad https://github.com/MoonchildProductions/moebius/pull/57
Style clean up - due to the surrounding code.
---
=> [minor fix] about:support - style clean up

toolkit/components/places/BookmarkHTMLUtils.jsm
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1046
---
=> [minor fix] Places - bookmarks - HTML export - write CRLF on Windows systems and LF on others

browser/components/places/content/treeView.js
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1020
---
=> [minor fix] Places - bookmarks - treeView.js - 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsINavHistoryContainerResultNode.getChildIndex]

browser/components/places/PlacesUIUtils.jsm, toolkit/components/places/PlacesUtils.jsm
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1137
---
=> [minor fix] Places - deleting folder of livemarks - nsLivemarkService.js - 0x80070057 (NS_ERROR_ILLEGAL_VALUE)

layout/generic/ReflowInput.cpp, layout/generic/ReflowInput.h, layout/generic/nsFrame.cpp, layout/generic/nsGridContainerFrame.cpp, layout/generic/nsIFrame.h, layout/reftests/css-grid/grid-item-overflow-stretch-001-ref.html, layout/reftests/css-grid/grid-item-overflow-stretch-001.html, layout/reftests/css-grid/grid-item-overflow-stretch-002-ref.html, layout/reftests/css-grid/grid-item-overflow-stretch-002.html, layout/reftests/css-grid/grid-item-overflow-stretch-003-ref.html, layout/reftests/css-grid/grid-item-overflow-stretch-003.html, layout/reftests/css-grid/grid-item-overflow-stretch-004-ref.html, layout/reftests/css-grid/grid-item-overflow-stretch-004.html, layout/reftests/css-grid/grid-item-overflow-stretch-005-ref.html, layout/reftests/css-grid/grid-item-overflow-stretch-005.html, layout/reftests/css-grid/grid-item-overflow-stretch-006-ref.html, layout/reftests/css-grid/grid-item-overflow-stretch-006.html, layout/reftests/css-grid/reftest.list
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1348857
An example:
https://bugzilla.mozilla.org/attachment.cgi?id=8849132
(expected results: https://bugzilla.mozilla.org/attachment.cgi?id=8849133)
---
=> CSS - Grid - intristic content with overflow:auto overlaps in grid

image/DrawResult.h, layout/forms/nsFieldSetFrame.cpp, layout/forms/nsFieldSetFrame.h, layout/forms/nsHTMLButtonControlFrame.cpp, layout/forms/nsHTMLButtonControlFrame.h, layout/forms/nsLegendFrame.h, layout/forms/nsTextControlFrame.cpp, layout/forms/nsTextControlFrame.h, layout/reftests/bugs/315920-17.html, layout/reftests/forms/display-block-baselines-1-ref.html, layout/reftests/forms/display-block-baselines-1.html, layout/reftests/forms/display-block-baselines-2-ref.html, layout/reftests/forms/display-block-baselines-2.html, layout/reftests/forms/display-block-baselines-3-ref.html, layout/reftests/forms/display-block-baselines-3.html, layout/reftests/forms/display-block-baselines-4-ref.html, layout/reftests/forms/display-block-baselines-4.html, layout/reftests/forms/display-block-baselines-5-ref.html, layout/reftests/forms/display-block-baselines-5.html, layout/reftests/forms/reftest.list
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1330962
An example:
https://bugzilla.mozilla.org/attachment.cgi?id=8826720
---
=> HTML - Forms - CSS - inline-block with a display:block <input> child element has a wrong baseline

dom/base/nsRange.cpp, dom/html/crashtests/1350972.html, dom/html/crashtests/crashtests.list
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1214 - `3)`
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1350972
Crashes:
https://bugzilla.mozilla.org/attachment.cgi?id=8851648
---
=> JS - DOM - Selection API - crashes

browser/base/content/browser-places.js
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1315 (https://github.com/MoonchildProductions/Pale-Moon/pull/1317).
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=625778
---
=> Places - Bookmarks - The context menu - After customize

devtools/client/locales/en-US/netmonitor.properties, devtools/client/netmonitor/shared/components/security-panel.js, devtools/client/netmonitor/test/browser_net_security-details.js, devtools/shared/webconsole/network-helper.js, security/manager/ssl/nsISSLStatus.idl, security/manager/ssl/nsNSSCallbacks.cpp, security/manager/ssl/nsNSSIOLayer.cpp, security/manager/ssl/nsSSLStatus.cpp, security/manager/ssl/nsSSLStatus.h
__Display key exchange and signature type for TLS 1.3__
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1304923
---
---
=> DevTools - network - security (improvements)

security/manager/ssl/nsNSSCallbacks.cpp
Ad https://github.com/MoonchildProductions/moebius/pull/113 (follow up)
\+ minor style clean up
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1396463
---
---
=> DevTools - network - security (follow up)

security/certverifier/NSSCertDBTrustDomain.cpp
=> [very minor fix] Fix typo in a comment

netwerk/protocol/http/nsHttpHandler.h
Followup to commit 02b4c0f.
Just what it says in the tin.
=> Fix GCC -Wreorder warning

addon-sdk/source/lib/dev/volcan.js, addon-sdk/source/lib/sdk/lang/weak-set.js, devtools/client/sourceeditor/tern/def.js, layout/base/nsLayoutUtils.cpp, xpfe/appshell/nsWindowMediator.cpp
See https://github.com/MoonchildProductions/Pale-Moon/pull/1400
=> [build, suggestion] Building with "--enable-debug" - fix some warnings

browser/installer/package-manifest.in
Just what it says in the tin. Fixes packaging after commit 7c39bd3.
=> Fix browser packaging

devtools/shared/gcli/commands/screenshot.js
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1466
---
---
=> DevTools - gcli - screenshot - the vertical mode

devtools/client/netmonitor/test/browser_net_curl-utils.js, devtools/client/shared/curl.js
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1471 (you add the label `Devtools`, please)
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1031956
https://bugzilla.mozilla.org/show_bug.cgi?id=1353535
---
=> DevTools - network - Copy as cURL (POST)

browser/components/migration/FirefoxProfileMigrator.js, browser/components/migration/MigrationUtils.jsm, toolkit/modules/ResetProfile.jsm, toolkit/xre/nsAppRunner.cpp
Ad #183 
__Add migration data (`...sqlite-wal`, hard-code strings):__
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1388611
See also:
https://github.com/MoonchildProductions/Pale-Moon/pull/1481
---
=> The profile - resetting (doesn't work)

dom/interfaces/security/nsIContentSecurityPolicy.idl, dom/locales/en-US/chrome/security/csp.properties, dom/security/nsCSPParser.cpp, dom/security/nsCSPParser.h, dom/security/nsCSPUtils.cpp, dom/security/nsCSPUtils.h, dom/security/test/csp/file_frame_src.js, dom/security/test/csp/file_frame_src_child_governs.html, dom/security/test/csp/file_frame_src_frame_governs.html, dom/security/test/csp/file_frame_src_inner.html, dom/security/test/csp/file_spawn_service_worker.js, dom/security/test/csp/file_spawn_shared_worker.js, dom/security/test/csp/file_spawn_worker.js, dom/security/test/csp/file_worker_src.js, dom/security/test/csp/file_worker_src_child_governs.html, dom/security/test/csp/file_worker_src_script_governs.html, dom/security/test/csp/file_worker_src_worker_governs.html, dom/security/test/csp/mochitest.ini, dom/security/test/csp/test_child-src_worker.html, dom/security/test/csp/test_frame_src.html, dom/security/test/csp/test_worker_src.html, dom/security/test/gtest/TestCSPParser.cpp, dom/webidl/CSPDictionaries.webidl, testing/web-platform/meta/content-security-policy/worker-src/dedicated-fallback.sub.html.ini, testing/web-platform/meta/content-security-policy/worker-src/service-fallback.https.sub.html.ini, testing/web-platform/meta/content-security-policy/worker-src/shared-fallback.sub.html.ini
Ad #168 
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1302667
---
I've created the new build (x32, Windows) and __not tested__ (I haven't time to try it properly).
=> CSP 3 - support for "worker-src"

editor/libeditor/HTMLEditorDataTransfer.cpp, editor/libeditor/tests/mochitest.ini, editor/libeditor/tests/test_bug1306532.html
Ad #190 
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1306532
---
=> HTML - table - editor (contenteditable)

netwerk/protocol/http/nsHttpChannel.cpp, netwerk/test/mochitests/mochitest.ini, netwerk/test/mochitests/test_1396395.html
Ad #210 
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1396395
---
=> Two (and more) extensions together - http resume - basilisk crashes

dom/security/nsContentSecurityManager.cpp
A bad copy of the branchs/files some where, again. I'm sorry.
=> Consider blocking top level window data: URIs (follow up, build bustage)

browser/branding/branding-common.mozbuild, browser/installer/package-manifest.in
Ad https://github.com/MoonchildProductions/moebius/commit/306d9de217122337d3211f0094bd526ef3ca0c7f
=> Rename visualelementsmanifest to match executable (follow up, build/installer bustage)

browser/installer/package-manifest.in, browser/locales/en-US/chrome/browser-region/region.properties, browser/locales/en-US/chrome/browser/aboutDialog.dtd, browser/locales/en-US/chrome/browser/aboutHealthReport.dtd, browser/locales/en-US/chrome/browser/aboutPrivateBrowsing.dtd, browser/locales/en-US/chrome/browser/browser.properties, browser/locales/en-US/chrome/browser/customizableui/customizableWidgets.properties, browser/locales/en-US/chrome/browser/preferences/main.dtd, browser/locales/en-US/chrome/browser/preferences/preferences.properties, browser/locales/en-US/chrome/browser/syncSetup.properties, browser/locales/en-US/chrome/browser/tabbrowser.properties, browser/locales/en-US/chrome/browser/webrtcIndicator.properties, browser/locales/en-US/chrome/overrides/appstrings.properties, browser/locales/en-US/crashreporter/crashreporter-override.ini, browser/modules/webrtcUI.jsm
Ad #227 
The change of the application name - in strings (partially).
---
I've created the new build (x32, Windows) and tested (__a private tab__).
=> [suggestion] Basilisk vs. Firefox (in strings)

toolkit/components/console/jsconsole-clhandler.js
See also:
https://github.com/MoonchildProductions/Pale-Moon/pull/1019#issuecomment-318881525
---
=> -help (the command line) - the columns alignment (when redirected to a file)

toolkit/themes/linux/global/jar.mn
Ad:
https://github.com/MoonchildProductions/moebius/pull/248/commits/79b5726187b3803bb9a140be8dd3ffbec2dcf887
=> [minor fix] toolkit/themes/linux/global/jar.mn - style clean up (the columns alignment)

browser/themes/windows/browser-aero.css
=> Remove top margin which cuts off the menu bar on Windows

application/basilisk/base/content/baseMenuOverlay.xul, application/basilisk/themes/osx/preferences/preferences.css, application/basilisk/themes/osx/shared.inc
=> Fix depth of Mac theme includes to toolkit

application/basilisk/app/macbuild/Contents/Info.plist.in
=> Fix executable name for Mac

devtools/client/locales/en-US/storage.dtd, devtools/client/storage/storage.xul, devtools/client/storage/test/browser_storage_basic.js, devtools/client/storage/test/browser_storage_cookies_delete_all.js, devtools/client/storage/test/browser_storage_delete_tree.js, devtools/client/storage/test/storage-listings.html, devtools/client/storage/test/storage-secured-iframe.html, devtools/client/storage/test/storage-unsecured-iframe.html, devtools/client/storage/ui.js, devtools/server/actors/storage.js, devtools/shared/specs/storage.js
This resolves #336 (you add the label `Devtools`, please)
Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1336934
https://bugzilla.mozilla.org/show_bug.cgi?id=1402485
---
=> Added option to remove all session cookies for a specific domain

devtools/client/shared/moz.build, devtools/client/shared/natural-sort.js, devtools/client/shared/widgets/TableWidget.js, devtools/client/storage/test/browser_storage_overflow.js, devtools/client/storage/test/head.js, devtools/client/storage/test/storage-overflow.html, devtools/server/actors/storage.js, toolkit/content/license.html
This resolves #341 → You add the label `Devtools`, please
Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1073967
---
=> Columns are not sorted correctly (suggestion - using Natural Sort algorithm)

devtools/client/netmonitor/request-list-context-menu.js, devtools/client/netmonitor/utils/moz.build, devtools/client/netmonitor/utils/open-request-in-tab.js
This resolves #351 → You add the label `Devtools`, please
Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1220758
---
=> Properly pass postData into new tab

application/basilisk/installer/package-manifest.in
Ported from Pale Moon repository.
This resolves #315
=> Use RESPATH in installer manifest for Mac OS X
