MoonchildProductions/moebius

toolkit/moz.configure
The PR restores the option to build with only GTK2 (using the "--enable-default-toolkit=cairo-gtk2" mozconfig option).
Note that I have not actually compiled or tested a GTK2 build; this PR simply restores the possibility to produce one. Whether or not the build process completes successfully and how stable the resulting build would be must still be evaluated (#27).
=> Restore option to build GTK2

toolkit/forgetaboutsite/ForgetAboutSite.jsm
See:
https://github.com/MoonchildProductions/Pale-Moon/pull/1049/commits/19de4d9ea210cf6d7e3b16f0e3fc4c995c586254#diff-9ad3203adf6f751fcdb9b2103052b443L205
https://github.com/MoonchildProductions/Pale-Moon/pull/1049/commits/c8ce141eda7aafe421da79652b332b1710916620#diff-9ad3203adf6f751fcdb9b2103052b443L205
https://github.com/MoonchildProductions/Pale-Moon/pull/1049/commits/75f686c1460c1eface4e43e3dcf2310e25633d40#diff-9ad3203adf6f751fcdb9b2103052b443L203
(https://bugzilla.mozilla.org/show_bug.cgi?id=1358772)
You add the label `UXP-task`, please:
https://github.com/MoonchildProductions/Pale-Moon/pull/1049
(https://bugzilla.mozilla.org/show_bug.cgi?id=1247201)
---
It's a minor fix, but not tested!
=> [minor fix] ForgetAboutSite.jsm + a comment (add the label "UXP-task")

browser/themes/windows/browser-aero.css, browser/themes/windows/browser.css, browser/themes/windows/caption-buttons.svg, browser/themes/windows/compacttheme.css
Ref #31 
This ports our Windows 10 titlebar work over from Pale Moon, while mixing in with the Mozilla styling (for example, the `-moz-windows-accent-color-applies: 0` background is `hsl(235,33%,19%)`, like upstream). Some elements that were present in this and upstream already, such as the elements for `-moz-windows-default-theme: 0` were kept as-is under the assumption the rest of this is to be as close as possible to upstream.
I also ported our caption buttons over to this.
=> Use Windows 10 accent color as background

dom/media/webrtc/MediaEngine.h
A custom .mozconfig - the compile failed with the following errors:
```
[drive]:\[path]\dist\include\MediaEngine.h(228):
error C2872: 'ipc': ambiguous symbol
[drive]:\[path]\ipc\ipdl\_ipdlheaders\mozilla/ipc/PBackgroundSharedTypes.h(751):
note: could be 'mozilla::ipc'
[drive]:\[path]\dist\include\mozilla/dom/ipc/StructuredCloneData.h(33):
note: or       'mozilla::dom::ipc'
[drive]:\[path]\dist\include\MediaEngine.h(239):
error C2872: 'ipc': ambiguous symbol
[drive]:\[path]\ipc\ipdl\_ipdlheaders\mozilla/ipc/PBackgroundSharedTypes.h(751):
note: could be 'mozilla::ipc'
[drive]:\[path]\dist\include\mozilla/dom/ipc/StructuredCloneData.h(33):
note: or       'mozilla::dom::ipc'
[drive]:\[path]\dist\include\MediaEngine.h(330):
error C2872: 'ipc': ambiguous symbol …
```
=> Build - a custom .mozconfig - fix

devtools/client/scratchpad/scratchpad.xul
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1275
---
=> DevTools - Scratchpad - fix an old bug (Ctrl+Shift+R / Reload and Run)

devtools/client/inspector/test/browser.ini, devtools/client/inspector/test/browser_inspector_infobar_04.js, devtools/server/actors/highlighters/box-model.js
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1160
(https://bugzilla.mozilla.org/show_bug.cgi?id=1341580)
---
---
=> DevTools - Inspector - tooltip get element width/height wrong when browser zoomed

devtools/client/framework/test/browser_toolbox_textbox_context_menu.js, devtools/client/inspector/computed/test/browser_computed_search-filter_context-menu.js, devtools/client/inspector/rules/test/browser_rules_search-filter_context-menu.js, devtools/client/inspector/test/browser_inspector_search-filter_context-menu.js, editor/libeditor/HTMLEditorDataTransfer.cpp, editor/libeditor/TextEditorDataTransfer.cpp, editor/libeditor/tests/chrome.ini, editor/libeditor/tests/mochitest.ini, editor/libeditor/tests/test_pasteImgTextarea.html, editor/libeditor/tests/test_pasteImgTextarea.xul, widget/windows/nsClipboard.cpp, widget/windows/nsDataObj.cpp, widget/windows/nsDataObj.h
An example sites:
https://www.gitlab.com/
https://www.facebook.com/
https://www.whatsapp.com/ (probably - not tested)
See also:
https://forum.palemoon.org/viewtopic.php?f=29&t=15866
https://forum.palemoon.org/viewtopic.php?f=3&t=16168
> It comes with rich text editing for issues (like this forum), to insert quotes, code, etc in issue body or comments.
> I currently encounter this issue on this feature:
> \- copy/pasting an image from MS Word 2016 should upload it and insert its Gitlab uri
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1317322
---
I've created the new build (x32, Windows) and tested (gitlab).
=> DataTransfer - Pasting image from clipboard fails in some cases

devtools/shared/webconsole/network-monitor.js
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1252
An example:
https://blog.cloudflare.com/introducing-tls-1-3/
Throws an error in Browser Console:
```
"Handler function threw an exception:
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE)
[nsIHttpChannelInternal.remoteAddress]"
nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"
location: "JS frame ::
resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/shared/webconsole/network-monitor.js
:: _onResponseHeader :: line 1345" data: no]
Stack:
_onResponseHeader@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/shared/webconsole/network-monitor.js:1345:5
_dispatchActivity@resource://gre/modules/commonjs/toolkit/loader.js
-> …
```
=> [partial fix] DevTools - network - proxy - throws an errors (remoteAddress)

browser/base/content/sync/aboutSyncTabs.js, browser/components/sessionstore/content/aboutSessionRestore.js, toolkit/components/aboutcache/content/aboutCache.js, toolkit/modules/sessionstore/FormData.jsm
---
---
Throws an error in Browser Console:
```
formatURLPref: Couldn't get pref: app.releaseNotesURL
nsURLFormatter.js:143
formatURLPref: Couldn't get pref: app.vendorURL
nsURLFormatter.js:143
```
`app.releaseNotesURL` - see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1367145
---
---
Throws an error:
---
See also:
https://github.com/MoonchildProductions/Pale-Moon/commit/25752a3bc20c3b436d8c2fb85082b27540c3833f
---
---
Throws an error in Browser Console:
```
ReferenceError: CloudSync is not defined
aboutSyncTabs.js:186:1
```
---
---
`(*) Restore only the ones you want`
Throws an error in Browser Console:
```
TypeError: gStateObject is undefined
aboutSessionRestore.js:71:3
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
FormData.jsm:220:28
```
---
I've …
=> [minor fix] about:... - throws an errors

testing/marionette/interaction.js, testing/marionette/listener.js
See:
https://hg.mozilla.org/mozilla-central/rev/f4448d4bcf98
https://hg.mozilla.org/mozilla-central/rev/dbad3f1bb947
---
I've created the new build (x32, Windows) - but not tested.
=> [minor fix, testing] Fix Marionette's DateTimeValue when dom.forms.datetime is enabled

devtools/server/actors/css-properties.js
See:
https://hg.mozilla.org/mozilla-central/rev/1697080a4726
---
---
I've created the new build (x32, Windows).
=> [minor fix] DevTools - css - css-color-4 - fix typo

layout/style/nsCSSParser.cpp, layout/style/test/property_database.js
See:
https://github.com/w3c/csswg-drafts/issues/1162
https://bugzilla.mozilla.org/show_bug.cgi?id=1363292
An example:
https://codepen.io/anon/pen/VbMyNL
https://codepen.io/anon/pen/ZKXvPM
---
=> [draft] CSS - linear-gradient - zero (0) angle value without degree unit is not correctly interpreted

js/src/irregexp/RegExpEngine.cpp, js/src/irregexp/RegExpEngine.h, js/src/tests/ecma_6/RegExp/unicode-ignoreCase-word-boundary.js
See:
https://github.com/tc39/ecma262/pull/525
https://bugzilla.mozilla.org/show_bug.cgi?id=1338373
An example (Scratchpad):
``` javascript
function assertEq(a, b) {
console.log(a === b);
}
assertEq(/\b/iu.test('\u017F'), true);
assertEq(/\b/i.test('\u017F'), false);
assertEq(/\b/u.test('\u017F'), false);
assertEq(/\b/.test('\u017F'), false);
assertEq(/\b/iu.test('\u212A'), true);
assertEq(/\b/i.test('\u212A'), false);
assertEq(/\b/u.test('\u212A'), false);
assertEq(/\b/.test('\u212A'), false);
assertEq(/\B/iu.test('\u017F'), false);
assertEq(/\B/i.test('\u017F'), true);
assertEq(/\B/u.test('\u017F'), true);
assertEq(/\B/.test('\u017F'), true);
assertEq(/\B/iu.test('\u212A'), false);
assertEq(/\B/i.test('\u212A'), true);
assertEq(/\B/u.test('\u212A'), true);
assertEq(/\B/.test('\u212A'), …
```
=> JS - RegExp - match updated spec for `/\b/iu` and `/\B/iu`

layout/base/nsLayoutUtils.cpp, layout/base/nsLayoutUtils.h, layout/generic/nsGridContainerFrame.cpp, layout/reftests/css-grid/grid-auto-min-sizing-min-content-min-size-004-ref.html, layout/reftests/css-grid/grid-auto-min-sizing-transferred-size-004-ref.html, layout/reftests/css-grid/grid-min-content-min-sizing-transferred-size-004-ref.html
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1349320
An example:
http://labs.jensimmons.com/2017/01-012-bug.html
(https://monosnap.com/file/bEj3Tm1PxuAI9z51lfK1UYMh1EGSPn.png)
http://labs.jensimmons.com/2017/01-013-bug.html
http://labs.jensimmons.com/2017/01-016-bug.html
---
=> CSS - Grid - transferred min-size contribution of percentage size grid item with an intrinsic ratio

devtools/client/locales/en-US/netmonitor.properties, devtools/client/netmonitor/components/summary-button.js, devtools/client/netmonitor/selectors/index.js, devtools/client/netmonitor/selectors/moz.build, devtools/client/netmonitor/selectors/requests.js, devtools/client/netmonitor/selectors/timing-markers.js, devtools/client/netmonitor/statistics-view.js, devtools/client/netmonitor/test/browser_net_charts-03.js, devtools/client/netmonitor/test/browser_net_charts-04.js, devtools/client/netmonitor/test/browser_net_charts-05.js, devtools/client/netmonitor/test/browser_net_charts-07.js, devtools/client/netmonitor/test/browser_net_footer-summary.js, devtools/client/shared/widgets/Chart.js
- Show transferred size in request summary instead of decompressed size
- Show DOMContentLoaded and load marker times
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1168376
https://bugzilla.mozilla.org/show_bug.cgi?id=1350228 (partially)
Before / After:
---
---
=> DevTools - network - improvements (transferred size, DOMContentLoaded and load)

devtools/client/inspector/rules/models/rule.js, devtools/client/inspector/rules/test/browser_rules_style-editor-link.js, devtools/shared/inspector/css-logic.js
Before:
After:
An example (Scratchpad):
``` javascript
var STYLESHEET_DATA_URL_CONTENTS = ["#first {",
"color: blue;",
"color: blue;",
"color: blue;",
"color: blue;",
"color: blue;",
"color: blue;",
"color: blue;",
"color: blue;",
"color: blue;",
"color: blue;",
"color: blue;",
"}"].join("\n");
var STYLESHEET_DATA_URL =
`data:text/css,${encodeURIComponent(STYLESHEET_DATA_URL_CONTENTS)}`;
var DOCUMENT_URL = "data:text/html;charset=utf-8," + encodeURIComponent(`
<html>
<head>
<title>Rule view style editor link test</title>
<style type="text/css">
html { color: #000000; }
div { font-variant: small-caps; color: #000000; }
.nomatches {color: #ff0000;}</style> <div id="first" style="margin: 10em;
font-size: 14pt; font-family: helvetica, sans-serif; color: #AAA">
</style>
<style>
div { …
```
=> DevTools - inspector - data URL source links and their tooltips are unreadable

docshell/base/nsDSURIContentListener.cpp, docshell/base/nsDSURIContentListener.h, dom/base/nsDocument.cpp, dom/base/nsDocument.h, dom/interfaces/security/nsIContentSecurityPolicy.idl, dom/locales/en-US/chrome/security/csp.properties, dom/security/nsCSPContext.cpp, dom/security/test/csp/file_ignore_xfo.html, dom/security/test/csp/file_ignore_xfo.html^headers^, dom/security/test/csp/file_ro_ignore_xfo.html, dom/security/test/csp/file_ro_ignore_xfo.html^headers^, dom/security/test/csp/mochitest.ini, dom/security/test/csp/test_ignore_xfo.html
https://www.w3.org/TR/CSP2/#frame-ancestors-and-frame-options
> The frame-ancestors directive obsoletes the X-Frame-Options header. If a resource has both policies, the frame-ancestors policy SHOULD be enforced and the X-Frame-Options policy SHOULD be ignored.
An example:
```
<?php
header('Content-Security-Policy: frame-ancestors http://localhost;');
header('X-Frame-Options: DENY');
?>
<html>
<head>
</head>
<body>
</body>
</html>
```
Expected results (the Browser Console):
```
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
```
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1024557
---
=> CSP 2 - ignore (x-)frame-options if CSP with frame-ancestors directive exists

browser/themes/shared/incontentprefs/preferences.inc.css
An example - `about:config`:
`intl.uidirection.en-US` = `rtl`
Before:
After:
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1217907
---
=> [minor fix] about:preferences#general homepage - [RTL] wrong direction

browser/base/content/test/plugins/browser.ini, browser/base/content/test/plugins/browser_subframe_access_hidden_plugins.js, dom/base/nsPluginArray.cpp
__Steps to reproduce:__
On Nightly with the default pref "plugins.navigator.hidden_ctp_plugin" set to "Shockwave Flash"
Set Flash as ask-to-activate
Load http://www.kongregate.com/games/Ninjakiwi/bloons-monkey-city
See the "Manage plug-in use" icon, click it and choose "Activate Now"
Reload the page
__Actual results:__
The page continues to say Flash is not available
__Expected results:__
The page should load with Flash activated
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1312091
---
=> Plugins - Cross-origin iframe hides Flash from navigator.plugins even when the Flash status is "always activate"

toolkit/content/widgets/datepicker.js
Ad #92 (improvements)
[Bug 1331608](https://bugzilla.mozilla.org/show_bug.cgi?id=1331608) - [DateTimePicker] months appear twice or not at all in month picker due to daylight savings time (e.g. March, October)
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1370671
---
I've created the new build (x32, Windows) but I have no example for this now.
=> HTML - input - datetime - Datepicker shows incorrect month for the first day of the month

browser/base/content/browser.js, browser/components/sessionstore/SessionStore.jsm, devtools/bootstrap.js, devtools/client/commandline/test/browser_cmd_commands.js, devtools/client/devtools-startup.js, devtools/client/framework/toolbox.js, devtools/client/menus.js, devtools/client/scratchpad/scratchpad.js, devtools/client/scratchpad/test/browser_scratchpad_open_error_console.js, devtools/client/webconsole/hudservice.js, devtools/client/webconsole/panel.js, devtools/client/webconsole/test/browser.ini, devtools/client/webconsole/test/browser_console.js, devtools/client/webconsole/test/browser_console_restore.js, devtools/client/webconsole/test/head.js, toolkit/components/extensions/ext-c-backgroundPage.js, toolkit/components/extensions/test/mochitest/test_chrome_ext_background_page.html
__Restore the Browser Console window__
An example:
- Open the Browser Console
- Restart the browser
(The menu: Help - Troubleshooting Information - Restart normally...)
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1388552 (partially)
---
---
=> DevTools - Browser Console - restore sessions

toolkit/components/passwordmgr/nsLoginManagerPrompter.js
__Steps to reproduce__
- open the browser (a non-private window)
- go to: https://github.com/greasemonkey/greasemonkey/issues/1717
- go to: http://kraehen.org/test/test.user.js (with HTTP Digest Auth)
(enter the correct login and password for authentication)
- open new private window
- go to: https://github.com/greasemonkey/greasemonkey/issues/1717
- go to: http://kraehen.org/test/test.user.js (with HTTP Digest Auth)
Throws an errors in Browser Console:
```
TypeError: win.gBrowser is undefined
nsLoginManagerPrompter.js:1426:11
nsPrompter: Delegation to password manager failed:
[Exception... "[JavaScript Error: "win.gBrowser is undefined"
{file: "resource://gre/components/nsLoginManagerPrompter.js" line: 1426}]
'[JavaScript Error: "win.gBrowser is undefined"
{file: …
```
=> Login Manager Prompter - auth - throws an errors

security/certverifier/CertVerifier.cpp, security/certverifier/NSSCertDBTrustDomain.cpp, security/manager/ssl/tests/unit/test_cert_trust.js
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1332
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1294580
---
I've created the new build (x32, Windows) but __not tested__.
=> [suggestion] (Windows) Security - Certificate Stores - NSSCertDBTrustDomain allows end-entities to be their own trust anchors

dom/base/nsDocument.cpp, dom/base/nsIDocument.h, dom/html/nsHTMLDocument.cpp, dom/html/nsHTMLDocument.h, dom/webidl/Document.webidl, dom/webidl/HTMLDocument.webidl, dom/webidl/Selection.webidl, layout/generic/Selection.h, layout/generic/nsSelection.cpp, testing/web-platform/meta/selection/getSelection.html.ini
Ad #120
__Steps to reproduce__
Go to:
HTML:
\- http://www.palemoon.org/
XML:
\- https://www.w3schools.com/xml/note.xml
\- Select some text
\- Scratchpad:
`alert(document.getSelection() + " / " + document.getSelection().type);`
__Expected results:__
[selected text] /  [None | Caret | Range]
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=718711
https://bugzilla.mozilla.org/show_bug.cgi?id=1359157
---
=> JS - DOM - Selection API - getSelection() should exist on XMLDocument / Selection.type

dom/events/EventDispatcher.cpp, testing/web-platform/meta/dom/events/EventTarget-dispatchEvent.html.ini, testing/web-platform/meta/dom/nodes/Document-createEvent.html.ini
Ad #122
__Steps to reproduce__
Scratchpad:
`alert(document.createEvent("FocusEvent"));`
Actual results:
`Exception: NotSupportedError: Operation is not supported`
Expected results:
[object FocusEvent]
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1388069
---
=> JS - DOM - Events - support createEvent("FocusEvent")

devtools/client/styleeditor/StyleEditorUI.jsm, devtools/client/styleeditor/test/browser.ini, devtools/client/styleeditor/test/browser_styleeditor_add_stylesheet.js, devtools/client/styleeditor/test/browser_styleeditor_import.js, devtools/server/actors/stylesheets.js, devtools/shared/specs/stylesheets.js
__An example:__
http://www.valuewalk.com/
https://bugzilla.mozilla.org/attachment.cgi?id=8688318
(no stylesheets are displayed)
__See:__
https://bugzilla.mozilla.org/show_bug.cgi?id=1224558
(https://bugzilla.mozilla.org/show_bug.cgi?id=1222991)
---
---
=> DevTools - style editor - StyleSheetsActor should use the parent tabActor to retrieve the list of windows and react to new/removed windows

media/ffvpx/ffvpxcommon.mozbuild
Just what it says in the tin. Silence warnings we don't particularly care about in 3rd party code with all supported compilers.
Built with GCC 5.3 and lightly tested. No issues seen.
=> Silence compiler warnings

docshell/test/unit/test_nsDefaultURIFixup_search.js, netwerk/base/nsStandardURL.cpp, netwerk/test/unit/test_URIs.js, netwerk/test/unit/test_standardurl.js, testing/web-platform/meta/url/a-element-xhtml.xhtml.ini, testing/web-platform/meta/url/a-element.html.ini, testing/web-platform/meta/url/url-constructor.html.ini
Follow up #133 - this change did not happen at all (after reverts).
An example (Scratchpad; `Environment` - `Browser`):
``` javascript
var StandardURL = Components.Constructor("@mozilla.org/network/standard-url;1",
"nsIStandardURL",
"init");
var nsIStandardURL = Components.interfaces.nsIStandardURL;
function stringToURL(str) {
return (new StandardURL(nsIStandardURL.URLTYPE_AUTHORITY, 80,
str, "UTF-8", null))
.QueryInterface(Components.interfaces.nsIURL);
}
function do_check_eq(a, b) {
var result = null;
if (a == b) {
result = true;
} else {
result = false;
}
console.log(result + ": (" + a + " == " + b + ")");
}
var url = stringToURL("http://a:@example.com");
do_check_eq(url.spec, "http://a@example.com/");
url.password = "pp";
do_check_eq(url.spec, "http://a:pp@example.com/");
url.password …
```
=> (follow up) URL parser - stop preserving empty passwords

dom/base/Element.cpp, dom/base/nsDocument.cpp, dom/base/nsINode.cpp, layout/base/RestyleManagerBase.cpp, layout/base/nsCSSFrameConstructor.cpp, layout/base/nsChangeHint.h, layout/base/nsPresContext.cpp, layout/base/nsPresContext.h, layout/reftests/scrolling/propagated-overflow-style-1-ref.html, layout/reftests/scrolling/propagated-overflow-style-1a.html, layout/reftests/scrolling/propagated-overflow-style-1b.html, layout/reftests/scrolling/propagated-overflow-style-1c.html, layout/reftests/scrolling/propagated-overflow-style-2-ref.html, layout/reftests/scrolling/propagated-overflow-style-2a.html, layout/reftests/scrolling/propagated-overflow-style-2b.html, layout/reftests/scrolling/propagated-overflow-style-2c.html, layout/reftests/scrolling/propagated-overflow-style-2d.html, layout/reftests/scrolling/propagated-overflow-style-2e.html, layout/reftests/scrolling/reftest.list, layout/style/nsStyleStruct.cpp, layout/style/test/mochitest.ini, layout/style/test/test_dynamic_change_causing_reflow.html, layout/style/test/test_viewport_scrollbar_causing_reflow.html
__An example - but it is individual:__
---
__testcase 1__
(https://bugzilla.mozilla.org/attachment.cgi?id=8843501)
\- actual results:
\> 2000 ms
\- expected results:
\< 100 ms
---
__testcase 2__
(https://bugzilla.mozilla.org/attachment.cgi?id=8843503)
\- actual results:
\> 3000 ms
\- expected results:
\< 2000 ms
---
__testcase 3__
(https://bugzilla.mozilla.org/attachment.cgi?id=8843521)
\- actual results:
\> 3000 ms
\- expected results:
\< 2000 ms
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1361268
https://bugzilla.mozilla.org/show_bug.cgi?id=1344398
https://bugzilla.mozilla.org/show_bug.cgi?id=1364180
https://bugzilla.mozilla.org/show_bug.cgi?id=1367568
---
=> Optimize operations on root of deeply-nested frame tree

browser/themes/windows/browser-aero.css
Port of https://github.com/MoonchildProductions/Pale-Moon/commit/ffd696dc410a921e2a21a73327e7ea79ff260764 to UXP.
This differs slightly from the Pale Moon implementation, as this provides a default style, and uses it as inactive (since we override it with the accent-color variants otherwise). This simply reverts back to the default styling when there isn't an accent color in use.
=> Remove active window styling on Win10 when no accent color is applied

dom/fetch/InternalHeaders.cpp, dom/fetch/InternalHeaders.h, dom/tests/mochitest/fetch/test_headers_common.js, testing/web-platform/meta/fetch/api/headers/headers-basic.html.ini
An example:
``` javascript
var headers = new Headers([["1", "a"],["1", "b"]]);
for (let header of headers) {
console.log(header.toString() === ["1", "a, b"].toString());
}
headers = new Headers([["2", "a"], ["1", "b"], ["2", "b"]]);
var expected = [["1", "b"], ["2", "a, b"]];
var i = 0;
for (let header of headers) {
console.log(header.toString() === expected[i].toString());
i++;
}
console.log(i === 2);
```
Excpected result:
\- all values should be TRUE
See:
https://github.com/whatwg/fetch/issues/506
https://bugzilla.mozilla.org/show_bug.cgi?id=1396848
---
=> Fetch - Headers should sort and combine

toolkit/components/xulstore/XULStore.js
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1402
Launch command: basilisk "-migration -p" (and create a new profile)
After starting the browser, throws an error in Browser Console:
```
NS_ERROR_FAILURE: Component returned failure code:
0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get]
XULStore.js:66:0
NS_ERROR_FAILURE: Component returned failure code:
0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get]
XULStore.js:102:0
```
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1398136
https://bugzilla.mozilla.org/show_bug.cgi?id=1368567 (partially)
---
You add the label `Verification Needed` (for original function: https://github.com/MoonchildProductions/Pale-Moon/issues/759), please.
---
=> Launch command: basilisk "-migration -p" (throws an error)

build/moz.build
Was there something wrong with just sending all defines to preprocessed files?!
This resolves the application.ini/appdata issues.
=> Ensure propagation of MC_OFFICIAL to appini_defines

modules/libpref/init/all.js, toolkit/components/alerts/resources/content/alert.css, toolkit/components/alerts/resources/content/alert.js
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1420
IMHO: Even in this case it makes sense:
`dom.webnotifications.requireinteraction.enabled` = `false`, etc.
---
=> Notifications - user settings - the immediate duration of the alert

browser/confvars.sh
Just what it says on the shipping label
=> If 'export BASILISK_VERSION=1' is in mozconfig then use 55.0.YYYY.MM.DD as MOZ_APP_VERSION

devtools/server/actors/webconsole.js, dom/performance/PerformanceResourceTiming.cpp, dom/performance/PerformanceResourceTiming.h, dom/performance/PerformanceTiming.cpp, dom/performance/PerformanceTiming.h, dom/webidl/PerformanceResourceTiming.webidl, dom/workers/ServiceWorkerEvents.cpp, dom/workers/ServiceWorkerPrivate.cpp, dom/workers/ServiceWorkerPrivate.h, dom/workers/test/serviceworkers/chrome.ini, dom/workers/test/serviceworkers/test_devtools_serviceworker_interception.html, netwerk/base/nsINetworkInterceptController.idl, netwerk/base/nsITimedChannel.idl, netwerk/ipc/NeckoChannelParams.ipdlh, netwerk/protocol/http/HttpBaseChannel.cpp, netwerk/protocol/http/HttpBaseChannel.h, netwerk/protocol/http/HttpChannelChild.cpp, netwerk/protocol/http/HttpChannelParent.cpp, netwerk/protocol/http/HttpChannelParent.h, netwerk/protocol/http/InterceptedChannel.cpp, netwerk/protocol/http/InterceptedChannel.h, netwerk/protocol/http/NullHttpChannel.cpp, netwerk/protocol/http/nsHttpChannel.cpp, testing/web-platform/meta/service-workers/service-worker/performance-timeline.https.html.ini, testing/web-platform/meta/service-workers/service-worker/resource-timing.https.html.ini, testing/web-platform/tests/service-workers/service-worker/resource-timing.https.html, testing/web-platform/tests/service-workers/service-worker/resources/resource-timing-worker.js
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1405739
https://bugzilla.mozilla.org/show_bug.cgi?id=1191943
https://bugzilla.mozilla.org/show_bug.cgi?id=1168875
__An example (for Scratchpad):__
Go to: http://json-schema.org/examples.html
``` javascript
function print_start_and_end_properties(perfEntry, num) {
properties = ["connectStart", "connectEnd",
"domainLookupStart", "domainLookupEnd",
"fetchStart", 
"redirectStart", "redirectEnd",
"requestStart", 
"responseStart", "responseEnd",
"secureConnectionStart",
"workerStart"];
for (var i=0; i < properties.length; i++) {
var supported = properties[i] in perfEntry;
if (supported) {
var value = perfEntry[properties[i]];
console.log("...[" + num + "] " + properties[i] + " = " + value);
} else {
console.log("...[" + num + "] " + …
```
=> The Performance Resource Timing (improvements)

dom/security/nsCSPContext.cpp, dom/security/test/csp/file_frame_ancestors_ro.html, dom/security/test/csp/file_frame_ancestors_ro.html^headers^, dom/security/test/csp/mochitest.ini, dom/security/test/csp/test_frame_ancestors_ro.html
> Despite what the comment here says, there is nowhere in the W3C CSP spec stating
that frame-ancestors should be ignored in report-only mode.
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1380755
---
I've created the new build (x32, Windows) but __not tested__.
=> CSP - Support frame-ancestors in Content-Security-Policy-Report-Only

devtools/client/netmonitor/request-utils.js
__Steps to reproduce__
Turn DevTools on (`Tools` - `Web Developer` - `Network`)
Go to (e.g.): https://www.seznam.cz/
Throws an error in Browser Console:
```
A promise chain failed to handle a rejection.
Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
Date: Wed Nov 01 2017 20:39:04 GMT+0100
Full Message: String contains an invalid character
Full Stack:
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/client/netmonitor/request-utils.js
:: formDataURI :: line 107
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/client/netmonitor/requests-menu-view.js
:: RequestsMenuView.prototype.updateRequest< :: line 279
JS frame :: …
```
=> [minor fix] DevTools - Throws an error ("String contains an invalid character")

docshell/base/nsDocShell.cpp, dom/base/nsContentPolicy.cpp, dom/security/nsContentSecurityManager.cpp, netwerk/base/LoadInfo.cpp, netwerk/base/LoadInfo.h, netwerk/base/nsILoadInfo.idl
Ad #181
ContentSecurityManager needs to pass the correct context for `TYPE_DOCUMENT` loads.
AFAIK - see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1331740
(https://bugzilla.mozilla.org/show_bug.cgi?id=1329288)
---
You add the label `Verification Needed`, please.
---
=> DOM - nsIContentPolicy - context (document)

netwerk/protocol/http/Http2Session.cpp
This should prevent http2 sessions freezing and resolve #165.
=> Ensure we process FIN flags on all-padding final frames.

dom/events/Event.cpp, dom/events/test/pointerevents/mochitest.ini, dom/events/test/pointerevents/test_trigger_fullscreen_by_pointer_events.html, dom/events/test/pointerevents/test_trigger_popup_by_pointer_events.html, layout/base/PresShell.cpp, modules/libpref/init/all.js, testing/marionette/element.js, testing/marionette/error.js, testing/marionette/harness/marionette_harness/tests/unit/test_click.py, testing/marionette/test_error.js
Ad #194
Fix: Steps to reproduce - #194
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1346166
https://bugzilla.mozilla.org/show_bug.cgi?id=1346605
---
Fix: tests / marionette
I think it belongs to that: `dom.w3c_pointer_events.enabled` = true
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1357995
https://bugzilla.mozilla.org/show_bug.cgi?id=1359050
---
I've created the new build (x32, Windows) and tested (tests / marionette - __not tested__).
=> DOM - PointerEvent - improvements

browser/components/migration/tests/marionette/test_refresh_firefox.py, toolkit/xre/ProfileReset.cpp, toolkit/xre/ProfileReset.h, toolkit/xre/nsAppRunner.cpp
Ad https://github.com/MoonchildProductions/Pale-Moon/pull/1505, #183 (improvements)
Resetting profile should incorporate the custom profile name in the profile directory name instead of using `default`
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=883627
---
=> The profile - resetting (improvements)

browser/base/content/browser-syncui.js
__Steps to reproduce:__
`basilisk.exe -console`
Throws an error:
```
Full message: ReferenceError: CloudSync is not defined
Full stack:
_promiseUpdateUI/<@chrome://browser/content/browser-syncui.js:173:1
process@resource://gre/modules/Promise.jsm
-> resource://gre/modules/Promise-backend.js:917:23
walkerLoop@resource://gre/modules/Promise.jsm
-> resource://gre/modules/Promise-backend.js:801:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm
-> resource://gre/modules/Promise-backend.js:737:11
```
See:
https://github.com/MoonchildProductions/moebius/issues/197#issuecomment-346301269
See also:
https://github.com/MoonchildProductions/moebius/pull/65/files#diff-679a390485d733d60119ec137ee331afR186
---
=> Throws an error: CloudSync is not defined

browser/components/extensions/ext-commands.js, browser/components/extensions/test/browser/browser_ext_commands_getAll.js
Ad #218
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1337457
---
=> WebExtensions - add-on throws error on load when suggested_key is null / missing

browser/components/extensions/ext-commands.js, browser/components/extensions/test/browser/browser_ext_commands_onCommand.js
Ad #220
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1337545
---
=> [suggestion] WebExtensions - commands API does not support shortcuts with space or numbers

docshell/base/nsDocShell.cpp, docshell/base/nsDocShell.h, dom/locales/en-US/chrome/security/security.properties, dom/security/nsContentSecurityManager.cpp, dom/security/nsContentSecurityManager.h, dom/security/test/general/browser.ini, dom/security/test/general/browser_test_toplevel_data_navigations.js, dom/security/test/general/file_block_toplevel_data_navigation.html, dom/security/test/general/file_block_toplevel_data_navigation2.html, dom/security/test/general/file_block_toplevel_data_navigation3.html, dom/security/test/general/file_block_toplevel_data_redirect.sjs, dom/security/test/general/file_toplevel_data_meta_redirect.html, dom/security/test/general/file_toplevel_data_navigations.sjs, dom/security/test/general/mochitest.ini, dom/security/test/general/test_allow_opening_data_json.html, dom/security/test/general/test_allow_opening_data_pdf.html, dom/security/test/general/test_block_toplevel_data_img_navigation.html, dom/security/test/general/test_block_toplevel_data_navigation.html, dom/security/test/moz.build, modules/libpref/init/all.js, netwerk/base/nsIOService.cpp, netwerk/base/nsIOService.h
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1528
---
`security.data_uri.block_toplevel_data_uri_navigations` = `true`
__An examples:__
(temporarily: `security.csp.enable` = `false`)
https://hg.mozilla.org/mozilla-central/raw-file/9cd4b2d56258/dom/security/test/general/file_block_toplevel_data_navigation.html
https://hg.mozilla.org/mozilla-central/raw-file/9cd4b2d56258/dom/security/test/general/file_block_toplevel_data_navigation3.html
\+ __redirecting:__
https://hg.mozilla.org/mozilla-central/raw-file/d80fa4d12362/dom/security/test/general/file_toplevel_data_meta_redirect.html
---
__The following example does not work:__
https://hg.mozilla.org/mozilla-central/raw-file/9cd4b2d56258/dom/security/test/general/file_block_toplevel_data_navigation2.html
Throws an error in …
=> Consider blocking top level window data: URIs

docshell/base/nsDSURIContentListener.cpp, docshell/base/nsDocShell.cpp, dom/security/nsContentSecurityManager.cpp, dom/security/nsContentSecurityManager.h, dom/security/test/general/browser.ini, dom/security/test/general/browser_test_data_download.js, dom/security/test/general/browser_test_data_text_csv.js, dom/security/test/general/file_data_download.html, dom/security/test/general/file_data_text_csv.html, dom/security/test/general/test_block_toplevel_data_img_navigation.html, dom/security/test/general/test_block_toplevel_data_navigation.html, ipc/glue/BackgroundUtils.cpp, netwerk/base/LoadInfo.cpp, netwerk/base/LoadInfo.h, netwerk/base/nsILoadInfo.idl, netwerk/ipc/NeckoChannelParams.ipdlh
Ad:
https://github.com/MoonchildProductions/Pale-Moon/issues/1528
Ad PRs:
#223
---
`security.data_uri.block_toplevel_data_uri_navigations` = `true`
__Steps to reproduce:__
Go http://danml.com/download.html#TestUsages
Click the "text dataURL" button
(also visible in the download button on https://makecode.microbit.org)
__Actual results:__
Nothing
__Expected results:__
A save file dialog should appear
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1403641
---
__Steps to reproduce:__
Open Browser Console and write simple one liner which should create CSV file:
```
window.open('data:text/csv;base64,' + btoa(unescape(encodeURIComponent('my text;with;values'))));
```
__Actual results:__
It opens empty blocked page
__Expected results:__
It should save file
See: …
=> Consider blocking top level window data: URIs (part 2)

addon-sdk/source/test/addons/embedded-webextension/webextension/manifest.json, browser/base/content/test/general/browser_webext_update.json, devtools/client/aboutdebugging/test/addons/test-devtools-webextension-nobg/manifest.json, devtools/client/aboutdebugging/test/addons/test-devtools-webextension/manifest.json, devtools/client/aboutdebugging/test/browser_addons_reload.js, devtools/client/debugger/test/mochitest/addon-source/browser_dbg_addon_webext_contentscript/manifest.json, devtools/server/tests/unit/addons/web-extension-upgrade/manifest.json, devtools/server/tests/unit/addons/web-extension/manifest.json, devtools/server/tests/unit/addons/web-extension2/manifest.json, mobile/android/components/extensions/test/mochitest/test_ext_pageAction.html
Ad #232 (also - but this is not a solution to the problem)
`manifest.json`: applications.`gecko`
vs.
`manifest.json`: applications.`goanna`
See:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications
See also:
http://xref.palemoon.org/moebius-trunk/search?string=applications.gecko
applications.`goanna` - cannot currently be used
---
I've created the new build (x32, Windows), but __not tested__.
=> [suggestion] WebExtensions - gecko vs. goanna (tests)

js/xpconnect/src/ExportHelpers.cpp, js/xpconnect/tests/unit/test_exportFunction.js
This PR gives functions created via `exportFunction()` the same `.length()` as the function being exported.
This resolves #242.
Based on:
https://bugzilla.mozilla.org/show_bug.cgi?id=1081385
=> XPCOM: exportFunction() - Fix wrong .length attribute

devtools/client/devtools-startup.js
This resolves #249 (you add the label `Devtools`, please.)
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1338681
---
=> basilisk -jsdebugger - Import Console.jsm before calling console.[something]

toolkit/mozapps/extensions/internal/XPIProvider.jsm
=> Add ID from a signature if it isn't included in manifest.json

devtools/client/devtools-startup.js
This resolves #254 (you add the label `Devtools`, please)
---
=> Add support for -browserconsole (the command line)

toolkit/components/viewsource/content/viewSource-content.js, toolkit/components/viewsource/content/viewSource.js, toolkit/components/viewsource/content/viewSourceUtils.js
This is a low impact patch. I have tested all the entry points into `View Source` and they still work.
----
Tag #280
=> Undeprecate viewSource.xul's original/legacy API

toolkit/mozapps/extensions/content/extensions.js, toolkit/mozapps/extensions/content/extensions.xml, toolkit/mozapps/extensions/internal/XPIProvider.jsm
* Revert [WebExtensions - adding ID from an sign, if it isn't in manifest.json](https://github.com/MoonchildProductions/moebius/commit/7ede45b5f546363ab297c66601d96252c072d36d)
* Revert [Remove warning for "unsigned" extensions.](https://github.com/MoonchildProductions/moebius/commit/25384fde4edec1a003347fa4dc7d17436a003fa7)
* Get IDs for ID-less WebExtensions when verification against Mozilla's hard-coded CA is disabled
This resolves #277.
=> Get IDs for ID-less WebExtensions without breaking normal libJAR signature checking

devtools/client/scratchpad/scratchpad.js, devtools/client/sourceeditor/editor-commands-controller.js, devtools/client/sourceeditor/editor.js, devtools/client/sourceeditor/moz.build, devtools/client/styleeditor/StyleSheetEditor.jsm
=> Restore source-editor commands controller for scratchpad & styleeditor menus

devtools/server/actors/tab.js
This resolves #301 (you add the label `Devtools`, please)
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1430117
(https://bugzilla.mozilla.org/show_bug.cgi?id=1391940)
---
=> Checking NS_BINDING_ABORTED to avoid dispatching navigate event

toolkit/components/reader/ReaderMode.jsm
This resolves #303
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1364056
---
=> Don't try to use "doc" reference when it might be dead

python/mozbuild/mozbuild/jar.py, python/mozbuild/mozbuild/preprocessor.py
> 1:35.23 d:\Projects\Programming\palemoon\uxp\application\basilisk\components\preferences\main.js: WARNING: no preprocessor directives found
=> Preprocessor warnings should not be fatal errors

devtools/client/netmonitor/shared/components/headers-panel.js
This resolves https://github.com/MoonchildProductions/Pale-Moon/issues/1602 (you add the label `Devtools`, please)
Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1419401
=> Show the Status Line (e.g. "HTTP/2.0 200 OK") in raw headers (response)

toolkit/components/extensions/ExtensionContent.jsm
This resolves #327
Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1410415
(+ https://hg.mozilla.org/mozilla-central/rev/4806f6814163#l1.13)
---
=> Set a sandboxName on the WebExtensions Content Script sandboxes

config/printconfigsetting.py
platform.ini is never there at the beginning of a clean or restart of an incomplete build and this causes one of Mozilla's one off scripts to python crash even though it is not considered fatal to the build system.
This simply checks if file exists and if not exits 0 with a warning message. The Warning and errors are also refined so that one knows where they are coming from when it does its thing.
=> printconfigsettings.py python errors out because a file doesn't exist.

toolkit/components/search/moz.build, toolkit/identity/moz.build
`FirefoxAccounts.jsm` no longer should be preprocessed
`nsSearchService.js` **ABSOLUTELY** needs preprocessed
=> Fix preprocessing in moz.build files after recent patches

devtools/client/storage/test/browser.ini, devtools/client/storage/test/browser_storage_cookies_domain_port.js, devtools/client/storage/test/head.js, devtools/server/actors/storage.js
This resolves #345 → You add the label `Devtools`, please
Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1350525
---
=> Storage Inspector should trim port from hosts for cookies

devtools/shared/gcli/commands/cmd.js, devtools/shared/gcli/source/lib/gcli/commands/help.js, devtools/shared/locales/en-US/gcli.properties
This resolves #347 → You add the label `Devtools`, please
Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1419171
https://bugzilla.mozilla.org/show_bug.cgi?id=1359258
---
You add the label `String Changes`, please.
---
=> Fix "help cmd" and "cmd refresh" in the Developer Toolbar

devtools/client/shared/widgets/TableWidget.js, devtools/client/storage/test/browser_storage_sidebar_update.js, devtools/client/storage/ui.js
This resolves #349 → You add the label `Devtools`, please
Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1280548
---
=> Don't display storage-sidebar after deleting all cookies
